using UnityEngine;

namespace PhysicsWidgets2D
{
    /// <summary>
    /// Interface for physics components that modify contact behavior.
    ///
    /// Contact providers do not directly apply forces or modify Rigidbody2D
    /// state. Instead, they contribute ContactConstraint2D objects to the
    /// current PhysicsFrame2D.
    ///
    /// Examples:
    /// - Conveyor belts
    /// - Moving platforms
    /// - Rollers
    /// - Special friction surfaces
    /// </summary>
    public interface IContactProvider2D
    {
        /// <summary>
        /// Generates one or more contact constraints for a Rigidbody2D contact.
        ///
        /// This method is called by PhysicsReceiver2D when the body is touching
        /// a collider associated with this provider.
        ///
        /// Implementations should:
        /// - Read the contact point and normal.
        /// - Determine surface behavior.
        /// - Add constraints to the PhysicsFrame2D.
        ///
        /// Implementations should NOT:
        /// - Call Rigidbody2D.AddForce().
        /// - Change Rigidbody2D.velocity.
        /// - Move transforms.
        /// </summary>
        /// <param name="body">
        /// The Rigidbody2D currently receiving physics effects.
        /// </param>
        /// <param name="contact">
        /// Unity's contact information generated by Box2D.
        /// </param>
        /// <param name="frame">
        /// The current physics frame to contribute to.
        /// </param>
        void EvaluateContact(
            Rigidbody2D body,
            ContactPoint2D contact,
            PhysicsFrame2D frame);
    }
}