using System.Collections.Generic;
using UnityEngine;

namespace PhysicsWidgets2D
{
    /// <summary>
    /// Bridge between Unity Rigidbody2D physics and the PhysicsWidgets2D system.
    ///
    /// Attach this component to any GameObject containing a Rigidbody2D that
    /// should interact with custom physics widgets.
    ///
    /// This component:
    /// - Collects contact-based interactions.
    /// - Collects force-based interactions.
    /// - Collects volume-based interactions.
    /// - Builds a PhysicsFrame2D.
    /// - Passes the frame to PhysicsSolver2D.
    ///
    /// This component does not directly modify physics state.
    /// </summary>
    [RequireComponent(typeof(Rigidbody2D))]
    public class PhysicsReceiver2D : MonoBehaviour
    {
        private Rigidbody2D body;


        private PhysicsFrame2D frame;



        private readonly HashSet<IContactProvider2D>
            contactProviders =
            new HashSet<IContactProvider2D>();


        private readonly HashSet<IForceProvider2D>
            forceProviders =
            new HashSet<IForceProvider2D>();


        private readonly HashSet<IVolumeProvider2D>
            volumeProviders =
            new HashSet<IVolumeProvider2D>();



        private readonly ContactPoint2D[] contacts =
            new ContactPoint2D[32];



        private void Awake()
        {
            body = GetComponent<Rigidbody2D>();

            frame = new PhysicsFrame2D();
        }



        private void FixedUpdate()
        {
            CollectPhysicsFrame();


            PhysicsSolver2D.Instance
                .Solve(
                    body,
                    frame);
        }



        /// <summary>
        /// Builds the physics frame for this physics step.
        /// </summary>
        private void CollectPhysicsFrame()
        {
            frame.Reset();



            CollectContacts();


            CollectForceProviders();


            CollectVolumeProviders();
        }



        /// <summary>
        /// Collects all physical contacts generated by Unity Physics2D.
        ///
        /// Contact providers include:
        /// - conveyors
        /// - moving platforms
        /// - rollers
        /// </summary>
        private void CollectContacts()
        {
            int count =
                body.GetContacts(contacts);



            for(int i = 0; i < count; i++)
            {
                ContactPoint2D contact =
                    contacts[i];


                Collider2D other =
                    contact.collider;


                MonoBehaviour[] components =
                    other.GetComponents<MonoBehaviour>();


                for(int c = 0; c < components.Length; c++)
                {
                    if(components[c] is IContactProvider2D provider)
                    {
                        provider.EvaluateContact(
                            body,
                            contact,
                            frame);
                    }
                }
            }
        }



        /// <summary>
        /// Evaluates all registered force providers.
        /// </summary>
        private void CollectForceProviders()
        {
            foreach(IForceProvider2D provider
                in forceProviders)
            {
                provider.EvaluateForce(
                    body,
                    frame);
            }
        }



        /// <summary>
        /// Evaluates all registered volume providers.
        /// </summary>
        private void CollectVolumeProviders()
        {
            foreach(IVolumeProvider2D provider
                in volumeProviders)
            {
                provider.EvaluateVolume(
                    body,
                    frame);
            }
        }



        /// <summary>
        /// Registers a force provider.
        ///
        /// Usually called by trigger-based widgets.
        /// </summary>
        public void RegisterForceProvider(
            IForceProvider2D provider)
        {
            if(provider != null)
            {
                forceProviders.Add(provider);
            }
        }



        /// <summary>
        /// Removes a force provider.
        /// </summary>
        public void UnregisterForceProvider(
            IForceProvider2D provider)
        {
            if(provider != null)
            {
                forceProviders.Remove(provider);
            }
        }



        /// <summary>
        /// Registers a volume provider.
        /// </summary>
        public void RegisterVolumeProvider(
            IVolumeProvider2D provider)
        {
            if(provider != null)
            {
                volumeProviders.Add(provider);
            }
        }



        /// <summary>
        /// Removes a volume provider.
        /// </summary>
        public void UnregisterVolumeProvider(
            IVolumeProvider2D provider)
        {
            if(provider != null)
            {
                volumeProviders.Remove(provider);
            }
        }
    }
}